# Run checks on the piper branch to merge with the main branch.

name: Piper

on:
  push:
    branches: ["piper"]
  pull_request:
    branches: ["piper"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy 
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List branches
      run: git branch -a -r

    - name: List remote
      run: git remote -v
