# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run checks on the piper branch to merge with the main branch.

name: Piper

on:
  push:
    branches: ["piper"]
  pull_request:
    branches: ["piper"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy 
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Merge branch into main
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          const targetBranch = 'main'; 
          const sourceBranch = 'piper';

          execSync(`git checkout ${targetBranch}`);
          execSync(`git merge ${sourceBranch}`);
          execSync(`git push origin ${targetBranch}`);
